name: orchio

services:
  postgres:
    image: postgres:15-alpine
    container_name: orchio-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchiodb
    ports:
      - "5447:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - orchio-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: orchio-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - orchio-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: orchio-kafka
    depends_on:
      - zookeeper
    ports:
      - "9047:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9047,INTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - orchio-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: orchio-kafka-ui
    ports:
      - "9048:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: orchio-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - orchio-network

volumes:
  postgres_data:

networks:
  orchio-network:
    driver: bridge
